### ISSUE TITLE
chairs dataset

### ISSUE THREAD

**Issue by ghailey** [zhenxuan00/graphical-gan#3]
may I ask that how to generate the chairs_64.npy?

**Comment by zhenxuan00** [comment]
see the convert_to_numpy function in tflib/chairs.py

**Comment by ghailey** [comment]
ok,I have generated it,but when I train the ssgan with chairs dataset ,it stop at one step,and don't continue.

**Comment by zhenxuan00** [comment]
have you changed the code? is there any warning or error?

**Comment by ghailey** [comment]
Yes

if MODE == 'local_ep': rec_penalty = None gen_cost, disc_cost, _, _, gen_train_op, disc_train_op = lib.objs.gan_inference.weighted_ampce


lib.objs.gan_inference.weighted_ampce  don't exist,so I change it to tflib.objs.gan_inference.weighted_local_epce

**Comment by zhenxuan00** [comment]
thanks for pointing it out. it seems to be a bug.

**Comment by ghailey** [comment]
SO how to change it

**Comment by zhenxuan00** [comment]
I think you're right. Now I have updated the code by using lib.objs.gan_inference.weighted_local_epce
note that I have imported tflib as lib. Thanks again.

**Comment by ghailey** [comment]
I still have a problem,when I run ssgan_inference_chairs.py,it stops at one step,like this:
[0.01612903 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903
 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903
 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903
 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903
 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903 0.01612903
 0.01612903 0.5       ]
2019-06-02 21:20:57.630638: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-02 21:20:58.091009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-06-02 21:20:58.091040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-02 21:20:58.329433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-02 21:20:58.329466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-06-02 21:20:58.329472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-06-02 21:20:58.329723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)

Totol number of parameters 9131550

Number of parameters in each player [1711251, 2785352, 4634947, 9131550]

**Comment by ghailey** [comment]
Thanks for your reply! Last problem was my fault.If I want to train the ssgan model with a new dataset,is it available?Do you have any suggestions? Thank you!

**Comment by zhenxuan00** [comment]
hi, I'm very glad if somebody tries to use ssgan in new scenarios. personally, I would suggest you to first extract all frames of the video datasets to form a new image dataset and try to train an ALI model at first. If it works, then use it as a frame generator and then build your dynamic networks upon that on the video datasets. If ALI can converge on the image dataset, then I believe ssgan will converge as well.

**Comment by zhenxuan00** [comment]
Actually, when I did experiments, I found the ALI part is very sensitive and you may need some efforts to get it to work.

**Comment by ghailey** [comment]
Thank you for your suggestions,I will try!

**Comment by zhenxuan00** [comment]
solved
